FROM eclipse-temurin:21-jdk-alpine

WORKDIR /workspace/app

ARG ID_LOG_VERSION=1.0.0-SNAPSHOT
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY src src
COPY libs libs
COPY templates templates
COPY .env .env

COPY .env /app/.env
RUN echo BUILDTIME=`date +%s%N | cut -b1-13` >> /app/.env

RUN ./mvnw install:install-file -Dfile=libs/id-log-${ID_LOG_VERSION}.jar -DgroupId=ee.ria.commons -DartifactId=id-log -Dversion=${ID_LOG_VERSION} -Dpackaging=jar -DgeneratePom=true
RUN ./mvnw -B dependency:go-offline dependency:resolve-plugins

ENTRYPOINT ["./mvnw", "-B", "test"]
